// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/category/domain/entity/category_obx_entity.dart';
import 'features/home/domain/entity/slider_obx_entity.dart';
import 'features/product/data/models/product_obx_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7545132289609355045),
    name: 'ProductObxEntity',
    lastPropertyId: const obx_int.IdUid(7, 3123709159275389220),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8534850047631112268),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 190999798989112701),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2390207174429900248),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8681479893887315377),
        name: 'price',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4783991946742012612),
        name: 'discount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 695349586930264697),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3123709159275389220),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5204027810725911480),
    name: 'SliderObxEntity',
    lastPropertyId: const obx_int.IdUid(2, 7683935926952498631),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1547701933059522272),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7683935926952498631),
        name: 'photo',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5887354731456482183),
    name: 'CategoryObxEntity',
    lastPropertyId: const obx_int.IdUid(6, 3101281100387813948),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8236956757099910838),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2827385691006067931),
        name: 'categoryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5797428397884092369),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6042703288794158423),
        name: 'banner',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5612090595006398194),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3101281100387813948),
        name: 'numberOfChildren',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 5887354731456482183),
    lastIndexId: const obx_int.IdUid(1, 6208428721871805051),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [6208428721871805051],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductObxEntity: obx_int.EntityDefinition<ProductObxEntity>(
      model: _entities[0],
      toOneRelations: (ProductObxEntity object) => [],
      toManyRelations: (ProductObxEntity object) => {},
      getId: (ProductObxEntity object) => object.id,
      setId: (ProductObxEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProductObxEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imageOffset = fbb.writeString(object.image);
        final priceOffset = fbb.writeString(object.price);
        final discountOffset = fbb.writeString(object.discount);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, imageOffset);
        fbb.addOffset(3, priceOffset);
        fbb.addOffset(4, discountOffset);
        fbb.addFloat64(5, object.rating);
        fbb.addInt64(6, object.productId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final productIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final imageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final priceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final discountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final ratingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ProductObxEntity(
          id: idParam,
          productId: productIdParam,
          name: nameParam,
          image: imageParam,
          price: priceParam,
          discount: discountParam,
          rating: ratingParam,
        );

        return object;
      },
    ),
    SliderObxEntity: obx_int.EntityDefinition<SliderObxEntity>(
      model: _entities[1],
      toOneRelations: (SliderObxEntity object) => [],
      toManyRelations: (SliderObxEntity object) => {},
      getId: (SliderObxEntity object) => object.id,
      setId: (SliderObxEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SliderObxEntity object, fb.Builder fbb) {
        final photoOffset = fbb.writeString(object.photo);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, photoOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final photoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = SliderObxEntity(id: idParam, photo: photoParam);

        return object;
      },
    ),
    CategoryObxEntity: obx_int.EntityDefinition<CategoryObxEntity>(
      model: _entities[2],
      toOneRelations: (CategoryObxEntity object) => [],
      toManyRelations: (CategoryObxEntity object) => {},
      getId: (CategoryObxEntity object) => object.id,
      setId: (CategoryObxEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryObxEntity object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final bannerOffset = object.banner == null
            ? null
            : fbb.writeString(object.banner!);
        final iconOffset = object.icon == null
            ? null
            : fbb.writeString(object.icon!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.categoryId);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, bannerOffset);
        fbb.addOffset(4, iconOffset);
        fbb.addInt64(5, object.numberOfChildren);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categoryIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final bannerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final numberOfChildrenParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = CategoryObxEntity(
          id: idParam,
          categoryId: categoryIdParam,
          name: nameParam,
          banner: bannerParam,
          icon: iconParam,
          numberOfChildren: numberOfChildrenParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductObxEntity] entity fields to define ObjectBox queries.
class ProductObxEntity_ {
  /// See [ProductObxEntity.id].
  static final id = obx.QueryIntegerProperty<ProductObxEntity>(
    _entities[0].properties[0],
  );

  /// See [ProductObxEntity.name].
  static final name = obx.QueryStringProperty<ProductObxEntity>(
    _entities[0].properties[1],
  );

  /// See [ProductObxEntity.image].
  static final image = obx.QueryStringProperty<ProductObxEntity>(
    _entities[0].properties[2],
  );

  /// See [ProductObxEntity.price].
  static final price = obx.QueryStringProperty<ProductObxEntity>(
    _entities[0].properties[3],
  );

  /// See [ProductObxEntity.discount].
  static final discount = obx.QueryStringProperty<ProductObxEntity>(
    _entities[0].properties[4],
  );

  /// See [ProductObxEntity.rating].
  static final rating = obx.QueryDoubleProperty<ProductObxEntity>(
    _entities[0].properties[5],
  );

  /// See [ProductObxEntity.productId].
  static final productId = obx.QueryIntegerProperty<ProductObxEntity>(
    _entities[0].properties[6],
  );
}

/// [SliderObxEntity] entity fields to define ObjectBox queries.
class SliderObxEntity_ {
  /// See [SliderObxEntity.id].
  static final id = obx.QueryIntegerProperty<SliderObxEntity>(
    _entities[1].properties[0],
  );

  /// See [SliderObxEntity.photo].
  static final photo = obx.QueryStringProperty<SliderObxEntity>(
    _entities[1].properties[1],
  );
}

/// [CategoryObxEntity] entity fields to define ObjectBox queries.
class CategoryObxEntity_ {
  /// See [CategoryObxEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryObxEntity>(
    _entities[2].properties[0],
  );

  /// See [CategoryObxEntity.categoryId].
  static final categoryId = obx.QueryIntegerProperty<CategoryObxEntity>(
    _entities[2].properties[1],
  );

  /// See [CategoryObxEntity.name].
  static final name = obx.QueryStringProperty<CategoryObxEntity>(
    _entities[2].properties[2],
  );

  /// See [CategoryObxEntity.banner].
  static final banner = obx.QueryStringProperty<CategoryObxEntity>(
    _entities[2].properties[3],
  );

  /// See [CategoryObxEntity.icon].
  static final icon = obx.QueryStringProperty<CategoryObxEntity>(
    _entities[2].properties[4],
  );

  /// See [CategoryObxEntity.numberOfChildren].
  static final numberOfChildren = obx.QueryIntegerProperty<CategoryObxEntity>(
    _entities[2].properties[5],
  );
}
